# -*- coding: utf-8 -*-
"""BMEG_project_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lf35ohhx-0ADFzTysUU6AChSKrxPE9Fh
"""

import pandas as pd

import numpy as np



"""# Data Preprocessing"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Replace 'MyFolder' with the actual name of your folder
# If it's inside other folders, use 'Folder1/Folder2/TargetFolder'
os.chdir('/content/drive/MyDrive/Colab Notebooks')

# Verify you are in the right place
print("Current Directory:", os.getcwd())
print("Files in folder:", os.listdir())

df = pd.read_csv('train_all_classes_merged.csv')
df1 = pd.read_csv('test_all_classes_merged.csv')

df

df1

df.columns

df1.columns

df_train = df.drop(columns = {'split','sample_file'})

df_train.columns

df_train.head(10)

df_train.shape

df_test = df1.drop(columns = {'split','sample_file'})
df_test.head(10)
df_test.shape

df_train = df_train.rename(columns = {'group':'target'})
df_test = df_test.rename(columns = {'group':'target'})

df_train.shape

df_test.shape

df_train.describe()

df_test.describe()

"""# Null Value Handling"""

df_train.isnull().sum()

df_test.isnull().sum()

"""# Data Type ColumnWise Check"""

df_train.dtypes

df_test.isnull().sum()

"""# Distribution Check of Variables"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define exclusions
primary_key = 'subject'  # Replace with your PK
target_code = 'target'  # Replace with your target
cols_to_analyze = [col for col in df_train.columns if col not in [primary_key, target_code]]

for col in cols_to_analyze:
    plt.figure(figsize=(8, 6))

    # Check if the column is categorical or numeric
    if df_train[col].dtype == 'object' or df_train[col].nunique() < 15:
        # Using your exact logic for categorical/discrete data
        counts = df_train[col].value_counts().sort_index()
        plt.bar(counts.index.astype(str), counts, color='deeppink')
        plt.title(f'Count Plot of {col}')
    else:
        # Use a histogram for continuous numerical data
        sns.histplot(df_train[col], kde=True, color='deeppink')
        plt.title(f'Distribution of {col}')

    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=45 if df_train[col].dtype == 'object' else 0)
    plt.tight_layout()
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define exclusions
primary_key = 'subject'  # Replace with your PK
target_code = 'target'  # Replace with your target
cols_to_analyze = [col for col in df_test.columns if col not in [primary_key, target_code]]

for col in cols_to_analyze:
    plt.figure(figsize=(8, 6))

    # Check if the column is categorical or numeric
    if df_test[col].dtype == 'object' or df_test[col].nunique() < 15:
        # Using your exact logic for categorical/discrete data
        counts = df_test[col].value_counts().sort_index()
        plt.bar(counts.index.astype(str), counts, color='deeppink')
        plt.title(f'Count Plot of {col}')
    else:
        # Use a histogram for continuous numerical data
        sns.histplot(df_test[col], kde=True, color='deeppink')
        plt.title(f'Distribution of {col}')

    plt.xlabel(col)
    plt.ylabel('Count')
    plt.xticks(rotation=45 if df_test[col].dtype == 'object' else 0)
    plt.tight_layout()
    plt.show()

"""# Model Execution

### Note: Everthing is done in 2 whole blocks, each step has been mentioned explicitly. Also Feature elimination step has been elminiated as well as outlier treatment since the data size was very small and would hamper the predictive power of a multiclassification model
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_is_fitted
from sklearn.metrics import (
    classification_report, accuracy_score,
    f1_score, recall_score, precision_score,
    balanced_accuracy_score, matthews_corrcoef,
    confusion_matrix, ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt

# ── 1. Drop subject & Encode Target ───────────────────────────────────────────
X_train = df_train.drop(columns=['subject', 'target'])
X_test  = df_test.drop(columns=['subject', 'target'])

# Fix object dtype — strip whitespace before encoding
df_train['target'] = df_train['target'].astype(str).str.strip()
df_test['target']  = df_test['target'].astype(str).str.strip()

le = LabelEncoder()
y_train = le.fit_transform(df_train['target'])  # AD→0, CN→1, MCI→2
y_test  = le.transform(df_test['target'])

print("Label Mapping :", dict(zip(le.classes_, le.transform(le.classes_))))
print("y_train dtype :", y_train.dtype)   # → int64
print("y_test  dtype :", y_test.dtype)    # → int64
print("Classes found :", le.classes_)     # → ['AD' 'CN' 'MCI']

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, label_binarize
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, StratifiedKFold
from sklearn.metrics import (
    classification_report, accuracy_score, f1_score,
    recall_score, precision_score, balanced_accuracy_score,
    matthews_corrcoef, confusion_matrix, ConfusionMatrixDisplay,
    roc_curve, auc, make_scorer
)
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# ── 1. Prepare Data ────────────────────────────────────────────────────────────
df_train['target'] = df_train['target'].astype(str).str.strip()
df_test['target']  = df_test['target'].astype(str).str.strip()

X_train = df_train.drop(columns=['subject', 'target'])
X_test  = df_test.drop(columns=['subject', 'target'])

le = LabelEncoder()
y_train = le.fit_transform(df_train['target'])   # AD→0, CN→1, MCI→2
y_test  = le.transform(df_test['target'])

# Binarize y_test for OvR AUC
classes    = le.classes_                          # ['AD', 'CN', 'MCI']
n_classes  = len(classes)
y_test_bin = label_binarize(y_test, classes=[0, 1, 2])   # shape (37, 3)

print("Label Mapping :", dict(zip(le.classes_, le.transform(le.classes_))))
print(f"X_train : {X_train.shape} | X_test : {X_test.shape}")


# ── 2. Define Scoring (Macro F1 as primary metric) ────────────────────────────
scoring = {
    'accuracy'          : make_scorer(accuracy_score),
    'macro_f1'          : make_scorer(f1_score,        average='macro', zero_division=0),
    'macro_recall'      : make_scorer(recall_score,    average='macro', zero_division=0),
    'macro_precision'   : make_scorer(precision_score, average='macro', zero_division=0),
    'balanced_accuracy' : make_scorer(balanced_accuracy_score),
}
REFIT_METRIC = 'macro_f1'   # ← Best model selected by Macro F1


# ── 3. Cross-Validation Strategy (Stratified for small dataset) ───────────────
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


# ── 4. Models + Hyperparameter Grids ──────────────────────────────────────────
models = {

    'Random Forest': {
        'pipeline': Pipeline([
            ('clf', RandomForestClassifier(random_state=42, class_weight='balanced'))
        ]),
        'params': {
            'clf__n_estimators'      : [50, 100, 200, 300],
            'clf__max_depth'         : [None, 3, 5, 10],
            'clf__min_samples_split' : [2, 5, 10],
            'clf__min_samples_leaf'  : [1, 2, 4],
            'clf__max_features'      : ['sqrt', 'log2'],
        },
        'search': 'random'   # RandomizedSearchCV (faster)
    },

    'Gradient Boosting': {
        'pipeline': Pipeline([
            ('clf', GradientBoostingClassifier(random_state=42))
        ]),
        'params': {
            'clf__n_estimators'  : [50, 100, 200],
            'clf__learning_rate' : [0.01, 0.05, 0.1, 0.2],
            'clf__max_depth'     : [2, 3, 5],
            'clf__subsample'     : [0.7, 0.8, 1.0],
            'clf__min_samples_split': [2, 5],
        },
        'search': 'random'
    },

    'SVM': {
        'pipeline': Pipeline([
            ('scaler', StandardScaler()),
            ('clf',    SVC(probability=True, class_weight='balanced', random_state=42))
        ]),
        'params': {
            'clf__C'      : [0.01, 0.1, 1, 10, 100],
            'clf__kernel' : ['linear', 'rbf', 'poly'],
            'clf__gamma'  : ['scale', 'auto', 0.001, 0.01, 0.1],
        },
        'search': 'grid'     # GridSearchCV (exhaustive)
    },

    'Logistic Regression': {
        'pipeline': Pipeline([
            ('scaler', StandardScaler()),
            ('clf',    LogisticRegression(max_iter=1000, class_weight='balanced',
                                          random_state=42, multi_class='multinomial'))
        ]),
        'params': {
            'clf__C'       : [0.001, 0.01, 0.1, 1, 10, 100],
            'clf__solver'  : ['lbfgs', 'saga'],
            'clf__penalty' : ['l2'],
        },
        'search': 'grid'
    },

    'KNN': {
        'pipeline': Pipeline([
            ('scaler', StandardScaler()),
            ('clf',    KNeighborsClassifier())
        ]),
        'params': {
            'clf__n_neighbors' : [3, 5, 7, 9, 11],
            'clf__weights'     : ['uniform', 'distance'],
            'clf__metric'      : ['euclidean', 'manhattan', 'minkowski'],
        },
        'search': 'grid'
    },
}


# ── 5. AUC Helper ─────────────────────────────────────────────────────────────
def compute_macro_auc(model, X_test, y_test_bin, n_classes):
    y_prob            = model.predict_proba(X_test)
    fpr, tpr, roc_auc = {}, {}, {}

    for i in range(n_classes):
        fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
        roc_auc[i]        = auc(fpr[i], tpr[i])

    all_fpr          = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))
    mean_tpr         = np.zeros_like(all_fpr)
    for i in range(n_classes):
        mean_tpr    += np.interp(all_fpr, fpr[i], tpr[i])
    mean_tpr        /= n_classes
    fpr['macro']     = all_fpr
    tpr['macro']     = mean_tpr
    roc_auc['macro'] = auc(all_fpr, mean_tpr)

    return fpr, tpr, roc_auc


# ── 6. Run Hyperparameter Tuning ───────────────────────────────────────────────
best_models  = {}
all_results  = []
auc_data     = {}

for name, config in models.items():
    print(f"\n{'═'*60}")
    print(f"  Tuning: {name}")
    print(f"{'═'*60}")

    if config['search'] == 'grid':
        search = GridSearchCV(
            estimator  = config['pipeline'],
            param_grid = config['params'],
            scoring    = scoring,
            refit      = REFIT_METRIC,
            cv         = cv,
            n_jobs     = -1,
            verbose    = 0,
            return_train_score=True
        )
    else:
        search = RandomizedSearchCV(
            estimator          = config['pipeline'],
            param_distributions= config['params'],
            n_iter             = 50,
            scoring            = scoring,
            refit              = REFIT_METRIC,
            cv                 = cv,
            n_jobs             = -1,
            verbose            = 0,
            random_state       = 42,
            return_train_score = True
        )

    search.fit(X_train, y_train)

    print(f"  Best Params  : {search.best_params_}")
    print(f"  Best CV {REFIT_METRIC}: {search.best_score_:.4f}")

    y_pred = search.best_estimator_.predict(X_test)

    acc      = accuracy_score(y_test,         y_pred)
    bal_acc  = balanced_accuracy_score(y_test, y_pred)
    mac_p    = precision_score(y_test, y_pred, average='macro',    zero_division=0)
    mac_r    = recall_score   (y_test, y_pred, average='macro',    zero_division=0)
    mac_f1   = f1_score       (y_test, y_pred, average='macro',    zero_division=0)
    wt_f1    = f1_score       (y_test, y_pred, average='weighted', zero_division=0)
    mcc      = matthews_corrcoef(y_test,        y_pred)

    # ── AUC ───────────────────────────────────────────────────────
    fpr, tpr, roc_auc = compute_macro_auc(
        search.best_estimator_, X_test, y_test_bin, n_classes
    )
    auc_data[name] = {'fpr': fpr, 'tpr': tpr, 'roc_auc': roc_auc}
    macro_auc       = roc_auc['macro']

    print(f"\n  ── Test Set Metrics ──────────────────────────────")
    print(f"  Accuracy          : {acc:.4f}")
    print(f"  Balanced Accuracy : {bal_acc:.4f}")
    print(f"  Macro Precision   : {mac_p:.4f}")
    print(f"  Macro Recall      : {mac_r:.4f}")
    print(f"  Macro F1          : {mac_f1:.4f}")
    print(f"  Weighted F1       : {wt_f1:.4f}")
    print(f"  Macro AUC         : {macro_auc:.4f}")
    print(f"  MCC               : {mcc:.4f}")
    print(f"\n  Per-Class AUC  →  ", end="")
    for i, cls in enumerate(classes):
        print(f"{cls}: {roc_auc[i]:.4f}", end="  ")
    print()
    print(f"\n  Classification Report:")
    print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

    best_models[name] = search.best_estimator_

    all_results.append({
        'Model'             : name,
        'Best CV Macro F1'  : round(search.best_score_, 4),
        'Accuracy'          : round(acc,       4),
        'Balanced Accuracy' : round(bal_acc,   4),
        'Macro Precision'   : round(mac_p,     4),
        'Macro Recall'      : round(mac_r,     4),
        'Macro F1'          : round(mac_f1,    4),
        'Weighted F1'       : round(wt_f1,     4),
        'Macro AUC'         : round(macro_auc, 4),
        'AUC-AD'            : round(roc_auc[0], 4),
        'AUC-CN'            : round(roc_auc[1], 4),
        'AUC-MCI'           : round(roc_auc[2], 4),
        'MCC'               : round(mcc,       4),
    })


# ── 7. Final Comparison Table ──────────────────────────────────────────────────
print(f"\n{'═'*70}")
print("  FINAL MODEL COMPARISON")
print(f"{'═'*70}")
results_df = pd.DataFrame(all_results).set_index('Model').sort_values('Macro F1', ascending=False)
print(results_df.to_string())

best_model_name = results_df['Macro F1'].idxmax()
print(f"\n  ✅ Best Model: {best_model_name} (Macro F1 = {results_df.loc[best_model_name, 'Macro F1']})")


# ── 8. Confusion Matrices — display order: CN → AD → MCI ──────────────────────
custom_order     = ['CN', 'MCI', 'AD']
custom_order_idx = [list(le.classes_).index(c) for c in custom_order]

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for idx, (name, model) in enumerate(best_models.items()):
    y_pred       = model.predict(X_test)
    cm           = confusion_matrix(y_test, y_pred)
    cm_reordered = cm[np.ix_(custom_order_idx, custom_order_idx)]
    disp         = ConfusionMatrixDisplay(confusion_matrix=cm_reordered, display_labels=custom_order)
    disp.plot(ax=axes[idx], colorbar=False, cmap='Blues')
    axes[idx].set_title(f"{name}\nMacro F1: {results_df.loc[name, 'Macro F1']}", fontsize=11)

for idx in range(len(best_models), len(axes)):
    axes[idx].set_visible(False)

plt.suptitle("Confusion Matrices — All Tuned Models", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()


# ── 9. ROC Curves — Per Model (3 classes + macro) ─────────────────────────────
colors = {'AD': '#e74c3c', 'CN': '#2ecc71', 'MCI': '#3498db', 'macro': '#2c3e50'}

fig, axes = plt.subplots(2, 3, figsize=(18, 11))
axes = axes.flatten()

for idx, (name, data) in enumerate(auc_data.items()):
    ax = axes[idx]
    for i, cls in enumerate(classes):
        ax.plot(
            data['fpr'][i], data['tpr'][i],
            color=colors[cls], lw=2,
            label=f"{cls} (AUC = {data['roc_auc'][i]:.3f})"
        )
    ax.plot(
        data['fpr']['macro'], data['tpr']['macro'],
        color=colors['macro'], lw=2.5, linestyle='--',
        label=f"Macro Avg (AUC = {data['roc_auc']['macro']:.3f})"
    )
    ax.plot([0, 1], [0, 1], 'k:', lw=1, label='Random (AUC = 0.500)')
    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 1.05])
    ax.set_xlabel('False Positive Rate', fontsize=9)
    ax.set_ylabel('True Positive Rate', fontsize=9)
    ax.set_title(f"{name}", fontsize=11, fontweight='bold')
    ax.legend(loc='lower right', fontsize=8)
    ax.grid(alpha=0.3)

for idx in range(len(auc_data), len(axes)):
    axes[idx].set_visible(False)

plt.suptitle("ROC Curves — All Models (One-vs-Rest per Class)", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()


# ── 10. Macro ROC Curve — All Models on One Plot ──────────────────────────────
model_colors = ['#e74c3c', '#e67e22', '#2ecc71', '#3498db', '#9b59b6']

fig, ax = plt.subplots(figsize=(9, 7))

for (name, data), color in zip(auc_data.items(), model_colors):
    ax.plot(
        data['fpr']['macro'], data['tpr']['macro'],
        lw=2.5, color=color,
        label=f"{name} (Macro AUC = {data['roc_auc']['macro']:.3f})"
    )

ax.plot([0, 1], [0, 1], 'k:', lw=1.5, label='Random Baseline (AUC = 0.500)')
ax.set_xlim([0.0, 1.0])
ax.set_ylim([0.0, 1.05])
ax.set_xlabel('False Positive Rate', fontsize=12)
ax.set_ylabel('True Positive Rate', fontsize=12)
ax.set_title('Macro-Average ROC Curve — All Models', fontsize=14, fontweight='bold')
ax.legend(loc='lower right', fontsize=10)
ax.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ── 11. Metric Comparison Bar Chart ───────────────────────────────────────────
metrics_to_plot = ['Accuracy', 'Macro F1', 'Macro Recall', 'Macro Precision', 'MCC']
plot_df = results_df[metrics_to_plot]

ax = plot_df.plot(kind='bar', figsize=(13, 6), colormap='Set2', edgecolor='black', width=0.75)
ax.set_title('Model Comparison — All Metrics', fontsize=14, fontweight='bold')
ax.set_xlabel('Model')
ax.set_ylabel('Score')
ax.set_ylim(0, 1.1)
ax.axhline(y=0.33, color='red', linestyle='--', linewidth=1, label='Random Baseline (0.33)')
ax.legend(loc='upper right', fontsize=9)
plt.xticks(rotation=15, ha='right')
plt.tight_layout()
plt.show()


# ── 12. Best Model — Final Predictions with Subject IDs ───────────────────────
best_clf       = best_models[best_model_name]
y_pred_final   = best_clf.predict(X_test)
y_pred_labels  = le.inverse_transform(y_pred_final)

final_df = pd.DataFrame({
    'subject'         : df_test['subject'].values,
    'true_label'      : df_test['target'].values,
    'predicted_label' : y_pred_labels,
    'correct'         : df_test['target'].values == y_pred_labels
})

print(f"\nBest Model Predictions ({best_model_name}):")
print(f"Correct: {final_df['correct'].sum()} / {len(final_df)}")
print(final_df.to_string(index=False))

